<?php

use Illuminate\Database\Seeder;
use App\User;
use App\Asignatura;

class Asignatura_UserTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /** Profesor - Asignatura */
        DB::table('asignatura_user')->insert([
            'user_id'=>'5',
            'asignatura_id'=>'1',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'5',
            'asignatura_id'=>'4',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'9',
            'asignatura_id'=>'5',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'14',
            'asignatura_id'=>'2',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'14',
            'asignatura_id'=>'10',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'16',
            'asignatura_id'=>'3',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'16',
            'asignatura_id'=>'6',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'18',
            'asignatura_id'=>'7',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'20',
            'asignatura_id'=>'8',
        ]);
        /** Estudiante - Asignatura */
        DB::table('asignatura_user')->insert([
            'user_id'=>'6',
            'asignatura_id'=>'1',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'6',
            'asignatura_id'=>'2',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'7',
            'asignatura_id'=>'3',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'7',
            'asignatura_id'=>'6',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'8',
            'asignatura_id'=>'7',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'8',
            'asignatura_id'=>'9',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'8',
            'asignatura_id'=>'2',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'8',
            'asignatura_id'=>'8',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'8',
            'asignatura_id'=>'10',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'10',
            'asignatura_id'=>'5',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'10',
            'asignatura_id'=>'4',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'11',
            'asignatura_id'=>'7',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'13',
            'asignatura_id'=>'1',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'13',
            'asignatura_id'=>'9',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'13',
            'asignatura_id'=>'2',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'15',
            'asignatura_id'=>'6',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'15',
            'asignatura_id'=>'1',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'17',
            'asignatura_id'=>'2',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'17',
            'asignatura_id'=>'1',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'19',
            'asignatura_id'=>'2',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'19',
            'asignatura_id'=>'8',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'21',
            'asignatura_id'=>'6',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'21',
            'asignatura_id'=>'7',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'21',
            'asignatura_id'=>'5',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'23',
            'asignatura_id'=>'10',
        ]);
        DB::table('asignatura_user')->insert([
            'user_id'=>'24',
            'asignatura_id'=>'10',
        ]);
    }
}

